name: quarto-publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          quarto-version: 1.9
      - name: Setup mermaid-cli
        uses: AnimMouse/setup-mermaid-cli@v1
      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - id: changed-files
        name: Check changed files
        uses: CCBR/actions/changed-files@latest
        with:
          paths: |
            **.mermaid
            **.mmd
            README.qmd

      - name: Render Mermaid diagram SVG
        if: contains(steps.changed-files.outputs.changed_files_json, '.mermaid') ||
          contains(steps.changed-files.outputs.changed_files_json, '.mmd')
        env:
          CHANGED_FILES_JSON: ${{ steps.changed-files.outputs.changed_files_json }}
        run: |
          
          for input in $(echo '${CHANGED_FILES_JSON}' | jq -r '.[] | select(endswith(".mermaid") or endswith(".mmd"))')
          do
            output="${input%.mermaid}.svg"
            output="${output%.mmd}.svg"
            mmdc -i "$input" -o "$output"
            git add "$output"
          done
          git commit -m "ci: 🧜‍♀️ update mermaid diagram SVGs" && git push || echo "nothing to commit"

      - name: render readme
        if: contains(steps.changed-files.outputs.changed_files_json, 'README.qmd')
        run: |
          quarto render README.qmd --to gfm --output README.md
          git add README.md
          git commit -m "ci: 📑 render readme" && git push || echo "nothing to commit"

      - name: Render website
        run: quarto render
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:

          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
